### ISSUE TITLE
Default Sorting

### ISSUE THREAD

**Issue by PromoFaux** [thisnameissoclever/ServiceNow-EfficientGlideRecord#3]
First of all - thanks for this library, landed here by chance after googling for something else, but certainly appreciating it a lot!

I wonder if I'm missing something, but doing `orderBy("fieldName")` seems to use alphabetical search by default, I could not find a way to sort numerically without pushing to an array and sorting myself, which is no biggy, but maybe there is a better way to be doing this...

In the example below, the `u_priority` field is an integer, The same happens when using the order field

```js
// default order by is alphabetical, no good on numbers! (e.g they come out as 1,10,11,2,3,30,4,5 etc)
// Create an array, add the eGR values to it as objects, and then sort it numerically.
var priorities = [];
while (eGR.next()) {
  priorities.push({
    val: eGR.getValue("u_priority"),
    label: eGR.getDisplayValue("u_priority"),
  });
}
priorities.sort(function (a, b) {
  return a.val - b.val;
});
```

**Comment by thisnameissoclever** [comment]
Hey @PromoFaux - this is the expected behavior based on the sorting mechanism in ServiceNow. Unfortunately I'm only able to do what SN does on the back-end using this library.
